### ISSUE TITLE
Change Branch Master to Main

### ISSUE THREAD

**Issue by AkashRajvanshi** [MatthieuBizien/roam-to-git#77] opened 2020-12-08 08:47 UTC
As per the new repositories in GitHub - The default branch is the main

```
# .github/workflows/main.yml
branches:
      - master
```

so as a new user commits the code, it will go to the main branch instead of master and which will not trigger an action.

```
# .github/workflows/main.yml
branches:
      - main
```

**Comment by everruler12** [comment] 2020-12-10 01:34
Duplicate of #56

**Closed** 2020-12-16 12:08 UTC
